name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get ctitv.m3u8
      run: |
        touch ./ctitv.m3u8
        sudo cat >./ctitv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/ctitv/live)
        EOL
    - name: Get ttvnews.m3u8
      run: |
        touch ./ttvnews.m3u8
        sudo cat >./ttvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/ttvnewsview/live)
        EOL
    - name: Get ftvnews.m3u8
      run: |
        touch ./ftvnews.m3u8
        sudo cat >./ftvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/FTVLIVE/live)
        EOL
    - name: Get ctsnews.m3u8
      run: |
        touch ./ctsnews.m3u8
        sudo cat >./ctsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/華視直播頻道/live)
        EOL
    - name: Get ctvnews.m3u8
      run: |
        touch ./ctvnews.m3u8
        sudo cat >./ctvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/twctvnews/live)
        EOL
    - name: Get setlive.m3u8
      run: |
        touch ./setlive.m3u8
        sudo cat >./setlive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/三立LIVE新聞/live)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/setmoney159/live)
        EOL
    - name: Get ebcnews.m3u8
      run: |
        touch ./ebcnews.m3u8
        sudo cat >./ebcnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/newsebc/live)
        EOL
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/寰宇新聞頻道/live)
        EOL
    - name: Get tvbsnews.m3u8
      run: |
        touch ./tvbsnews.m3u8
        sudo cat >./tvbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://https://www.youtube.com/c/TVBSNEWS01/live)
        EOL
    - name: Get cctv4.m3u8
      run: |
        touch ./cctv4.m3u8
        sudo cat >./cctv4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/ChineseInternatioify/live)
        EOL
    - name: Get eftv.m3u8
      run: |
        touch ./eftv.m3u8
        sudo cat >./eftv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/EFTV01/live)
        EOL
    - name: Get daai1.m3u8
      run: |
        touch ./daai1.m3u8
        sudo cat >./daai1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=oV_i3Hsl_zg)
        EOL
    - name: Get daai2.m3u8
      run: |
        touch ./daai2.m3u8
        sudo cat >./daai2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get daai3.m3u8
      run: |
        touch ./daai3.m3u8
        sudo cat >./daai3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/DaAiVideo/live)
        EOL
    - name: Get sdtv.m3u8
      run: |
        touch ./sdtv.m3u8
        sudo cat >./sdtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/channel/UCrVBXIxpYnjTk4ezn9F-fug/live)
        EOL
    - name: Get ctsshow.m3u8
      run: |
        touch ./ctsshow.m3u8
        sudo cat >./ctsshow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/TBSCTSSHOW/live)
        EOL
    - name: Get ebcyoyo.m3u8
      run: |
        touch ./ebcyoyo.m3u8
        sudo cat >./ebcyoyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get ctinews.m3u8
      run: |
        touch ./ctinews.m3u8
        sudo cat >./ctinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=lu_BJKxqGnk)
        EOL
    - name: Get gstv.m3u8
      run: |
        touch ./gstv.m3u8
        sudo cat >./gstv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/channel/UCoo-jAsJgM8z09ddlhcBlSA/live)
        EOL
    - name: Get parliamentarytv1.m3u8
      run: |
        touch ./parliamentarytv1.m3u8
        sudo cat >./parliamentarytv1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=PQLMD4iHhG8)
        EOL
    - name: Get parliamentarytv2.m3u8
      run: |
        touch ./parliamentarytv2.m3u8
        sudo cat >./parliamentarytv2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/c/國會頻道/live)
        EOL
    - name: Get abcnewsau.m3u8
      run: |
        touch ./abcnewsau.m3u8
        sudo cat >./abcnewsau.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/NewsOnABC/live)
        EOL
    - name: Get abcnewsus
      run: |
        touch ./abcnewsus.m3u8
        sudo cat >./abcnewsus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/ABCNews/live)
        EOL
    - name: Get abc7news
      run: |
        touch ./abc7news.m3u8
        sudo cat >./abc7news.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/channel/UCq9e_hCv2jvgck8WowW1NXg/live)
        EOL
    - name: Get ttvnews_sd.m3u8
      run: |
        touch ./ttvnews_sd.m3u8
        sudo cat >./ttvnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/ttvnewsview/live)
        EOL
    - name: Get ftvnews_sd.m3u8
      run: |
        touch ./ftvnews_sd.m3u8
        sudo cat >./ftvnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/FTVLIVE/live)
        EOL
    - name: Get ctsnews_sd.m3u8
      run: |
        touch ./ctsnews_sd.m3u8
        sudo cat >./ctsnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/華視直播頻道/live)
        EOL
    - name: Get ctvnews_sd.m3u8
      run: |
        touch ./ctvnews_sd.m3u8
        sudo cat >./ctvnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/twctvnews/live)
        EOL
    - name: Get setlive_sd.m3u8
      run: |
        touch ./setlive_sd.m3u8
        sudo cat >./setlive_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/三立LIVE新聞/live)
        EOL
    - name: Get setinews_sd.m3u8
      run: |
        touch ./setinews_sd.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/setmoney159/live)
        EOL
    - name: Get ebcnews_sd.m3u8
      run: |
        touch ./ebcnews_sd.m3u8
        sudo cat >./ebcnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/newsebc/live)
        EOL
    - name: Get hyxw_sd.m3u8
      run: |
        touch ./hyxw_sd.m3u8
        sudo cat >./hyxw_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/寰宇新聞頻道/live)
        EOL
    - name: Get tvbsnews_sd.m3u8
      run: |
        touch ./tvbsnews_sd.m3u8
        sudo cat >./tvbsnews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://https://www.youtube.com/c/TVBSNEWS01/live)
        EOL
    - name: Get cctv4_sd.m3u8
      run: |
        touch ./cctv4_sd.m3u8
        sudo cat >./cctv4_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/user/ChineseInternatioify/live)
        EOL
    - name: Get eftv_sd.m3u8
      run: |
        touch ./eftv_sd.m3u8
        sudo cat >./eftv_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/user/EFTV01/live)
        EOL
    - name: Get daai1_sd.m3u8
      run: |
        touch ./daai1_sd.m3u8
        sudo cat >./daai1_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/watch?v=oV_i3Hsl_zg)
        EOL
    - name: Get daai2_sd.m3u8
      run: |
        touch ./daai2_sd.m3u8
        sudo cat >./daai2.m3u8_sd <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get daai_sd3.m3u8
      run: |
        touch ./daai3._sdm3u8
        sudo cat >./daai3_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/user/DaAiVideo/live)
        EOL
    - name: Get sdtv_sd.m3u8
      run: |
        touch ./sdtv_sd.m3u8
        sudo cat >./sdtv_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/channel/UCrVBXIxpYnjTk4ezn9F-fug/live)
        EOL
    - name: Get ctsshow_sd.m3u8
      run: |
        touch ./ctsshow_sd.m3u8
        sudo cat >./ctsshow_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/TBSCTSSHOW/live)
        EOL
    - name: Get ebcyoyo_sd.m3u8
      run: |
        touch ./ebcyoyo_sd.m3u8
        sudo cat >./ebcyoyo_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get ctinews_sd.m3u8
      run: |
        touch ./ctinews_sd.m3u8
        sudo cat >./ctinews_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/watch?v=lu_BJKxqGnk)
        EOL
    - name: Get gstv_sd.m3u8
      run: |
        touch ./gstv_sd.m3u8
        sudo cat >./gstv_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/channel/UCoo-jAsJgM8z09ddlhcBlSA/live)
        EOL
    - name: Get parliamentarytv1_sd.m3u8
      run: |
        touch ./parliamentarytv1_sd.m3u8
        sudo cat >./parliamentarytv1_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/watch?v=PQLMD4iHhG8)
        EOL
    - name: Get parliamentarytv2_sd.m3u8
      run: |
        touch ./parliamentarytv2_sd.m3u8
        sudo cat >./parliamentarytv2_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/c/國會頻道/live)
        EOL
    - name: Get abcnewsau_sd.m3u8
      run: |
        touch ./abcnewsau_sd.m3u8
        sudo cat >./abcnewsau_sd.m3u8 <<EOL
        #EXTM3U_sd
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/user/NewsOnABC/live)
        EOL
    - name: Get abcnewsus_sd.m3u8
      run: |
        touch ./abcnewsus_sd.m3u8
        sudo cat >./abcnewsus_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/user/ABCNews/live)
        EOL
    - name: Get abc7news_sd.m3u8
      run: |
        touch ./abc7news_sd.m3u8
        sudo cat >./abc7news_sd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000
        $(youtube-dl -g https://www.youtube.com/channel/UCq9e_hCv2jvgck8WowW1NXg/live)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
